### ISSUE TITLE
Consider Changing "Fog" to "Raymarch" or even "Cloud"

### ISSUE THREAD

**Issue by DennisSmolek** [mjurczyk/openvdb#2]
In the context of WebGL and ThreeJS specifically "FOG" has a super old school hardware level implementation. There's also a few other "Fog" procedures common out there like "Height Fog" which is pseudo Volumetric.

Your implementation of the volume raymarcher is one of the most complete and most compatible to standard ThreeJS Scenes...

I saw the comment on the Project (out of date?) and I think theres a huge space for `MeshVolumeMaterial`

I think it's fine to be technical and call it what it is, raymarching.  But if you want it to be more visual I think "Cloud" would work for more circumstances than "fog"

**Comment by mjurczyk** [comment]
100% agree - a few points to think over after I'll have the first API version ready:
1) `Fog Volume` name has to stay, but only in the context of OpenVDB. It's an recognised OpenVDB grid class type ([example](https://github.com/AcademySoftwareFoundation/openvdb/blob/master/openvdb/openvdb/Grid.cc#L141).) 
2) BUT - [this](https://github.com/mjurczyk/openvdb/blob/main/src/openvdb/three/VolumeToFog.js#L80) kinda doesn't really belong to this repo / VDBLoader package. It's coded here right now only because there's no alternative to it in core three - and I don't want to over-engineer stuff by creating 1000 packages before the thing's even usable. But indeed, having volume material in a `VDBLoader` package feels like locking `MeshStandardMaterial` within `GLTFLoader` package - they are independent and can be used separately depending on the context.
3) Originally I wanted this repo to be independent of three. Not sure yet how it'll look in the end - but I'd like `VDBLoader` to also be accessible to folks using Babylon / pure WebGL - just as a data structure they are able to read from.

**Comment by DennisSmolek** [comment]
> 1. `Fog Volume` name has to stay, but only in the context of OpenVDB. It's an recognised OpenVDB grid class type ([example](https://github.com/AcademySoftwareFoundation/openvdb/blob/master/openvdb/openvdb/Grid.cc#L141).)
Oh I'm not saying it should be removed entirely, especially if it's so core to the names within OpenVDB itself (I didn't know that)

I guess I was more thinking about the editor, and the "Render Type" is either "BBOX" or "Fog" Which first confused me, then I thought was a catch all for any "Cloudy" stylization..

Looking at the different grid values, and from my brief conversation with the guys porting OpenVDB into Unreal, the Grid data has a TON of LevelSets.

Is that something you're already parsing and rendering or is that a render method you haven't implemented yet?

In that case it would make much more sense if "Fog Volume" was the only data you were rendering.

---

Regarding Three...

1. Do what you gotta do.. If it's easier to get off the ground with it I say no problem. 
2.Longer term you will probably move towards either direct NanoVDB implementation or at a minimum Raymarching on the GPU.
That seems like a perfect time to generalize the shaders/flow to be WebGL (hell GLSL) neutral if thats still a goal...



It's not something I'd even think about at the moment, but One thing you could do now is modularize the shaders a bit, like right now you're mixing loading the core three ones, overrides, your own volume lighting methods, and then at the final raymarch the big lighting builder pulling three globals etc...

If you say moved the "Lighting" to it's own file it'll be a little easier.

Also I didn't see anywhere your references for the renderer itself. Are you writing purely from scratch or did you base it on anything?

Is it a copy of Nano's?

I've been drowning in them over the past few weeks struggling to understand what the heck is going on.. So I've seen some things that might help or in other usecases make sense... I have no idea though and defer to others, I'm a total newb when going this deep.

I was mostly thinking about SebH's one https://www.shadertoy.com/view/XlBSRz

But also the Unreal5 clouds renderer which actually uses this 2010 simplification as the key basis: http://magnuswrenninge.com/wp-content/uploads/2010/03/Wrenninge-OzTheGreatAndVolumetric.pdf

I'm working on a bastardized version of everyones (and will probably steal your lights🤣)

Great work man, I'm super impressed and I know it's not easy..

Please let me know if I can help at all, I'm probably clueless but willing to dive into the research..
